apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webhook
  namespace: cluster-config
spec:
  interval: 5m
  targetNamespace: ingress-helper
  releaseName: webhook
  chart:
    spec:
      chart: webhook
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: webhook
        namespace: cluster-config
  values:
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector: # Selector to ensure pods are scheduled on the desired nodes
      system-pool: "true"
    affinity: # Additional affinity rules
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "system-pool"
                  operator: "In"
                  values:
                    - "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: cluster-config
spec:
  interval: 5m
  targetNamespace: ingress-helper
  releaseName: kubewatch
  chart:
    spec:
      chart: kubewatch
      version: "3.5.0"
      sourceRef:
        kind: HelmRepository
        name: kubewatch
        namespace: cluster-config
  values:
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector: # Selector to ensure pods are scheduled on the desired nodes
      system-pool: "true"
    affinity: # Additional affinity rules
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "system-pool"
                  operator: "In"
                  values:
                    - "true"
    slack:
      enabled: false
    rbac:
      create: true
    namespaceToWatch: ""
    resourcesToWatch:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: false
      pod: false
      job: false
      node: false
      clusterrole: false
      clusterrolebinding: false
      serviceaccount: false
      persistentvolume: false
      namespace: false
      secret: false
      configmap: false
      ingress: true
      coreevent: false
      event: false
    webhook:
      enabled: true
      url: "http://webhook.ingress-helper.svc.cluster.local:8080/hook"
