# ClusterRole for accessing Ingress resources across all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-reader-cluster-role
rules:
  # Permissions for ingress resources across all namespaces
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]

  # Optional: Permissions for other resources across all namespaces
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - namespaces
      - endpoints
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding to associate the ClusterRole with the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-reader-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-reader-cluster-role
subjects:
  - kind: ServiceAccount
    name: kubewatch # Correct ServiceAccount name
    namespace: ingress-helper

