apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-helper-role
  namespace: ingress-helper
rules:
  # Permissions for ingress resources
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]

  # Permissions for secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

  # Permissions for core resources
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - namespaces
      - endpoints
    verbs: ["get", "list", "watch"]

  # Permissions for apps resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]

  # Permissions for events
  - apiGroups: ["events.k8s.io", ""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-helper-rolebinding
  namespace: ingress-helper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-helper-role
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: ingress-helper

