---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: cluster-config
spec:
  targetNamespace: reloader
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector: # Selector to ensure pods are scheduled on the desired nodes
      system-pool: "true"
    affinity: # Additional affinity rules
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "system-pool"
                  operator: "In"
                  values:
                    - "true"
