---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: cluster-config
spec:
  selector:
    matchLabels:
      system-pool: "true"
  targetNamespace: reloader
  chart:
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
  interval: 10m0s
  install:
    remediation:
      retries: 3
