apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webhook
  namespace: cluster-config
spec:
  interval: 5m
  targetNamespace: webhook
  releaseName: webhook
  chart:
    spec:
      chart: webhook
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: webhook
        namespace: cluster-config
  values:
    image:
      repository: ghcr.io/amerintlxperts/webhook
      tag: "1.0.0"
    service:
      port: 8080

