apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webhook
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: webhook
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: webhook-repo
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/amerintlxperts/webhook
      tag: "1.0.0"
    service:
      port: 8080

