apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: webhook-handler-repo
  namespace: flux-system
spec:
  interval: 1h
  url: https://amerintlxperts.github.io/webhook/

