---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: cluster-config
spec:
  targetNamespace: gpu-operator
  releaseName: gpu-operator
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: gpu-operator
        namespace: cluster-config
  interval: 10m0s
  install:
    timeout: 20m
    remediation:
      retries: 5
  upgrade:
    timeout: 20m
  values:
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      nvidia.com/gpu: "true"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "system-pool"
                  operator: "NotIn"
                  values:
                    - "true"
    driver.enabled: true
    toolkit.enabled: true
    operator.runtimeClass: "nvidia-container-runtime"
