---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fortiweb-ingress-controller
  namespace: cluster-config
spec:
  selector:
    matchLabels:
      system-pool: "true"
  targetNamespace: fortiweb-ingress
  releaseName: fortiweb-ingress-controller
  chart:
    spec:
      chart: fwb-k8s-ctrl
      sourceRef:
        kind: HelmRepository
        name: fortiweb-ingress-controller
        namespace: cluster-config
      version: "2.0.1"
  interval: 10m0s
  values:
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  install:
    remediation:
      retries: 3
