---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rmordasiewicz@fortinet.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        azureDNS:
          resourceGroupName: amerintlxperts
          subscriptionID: {{ SUBSCRIPTION_ID }}
          hostedZoneName: amerintlxperts.com
          environment: AzurePublicCloud
          managedIdentity:
            clientID: {{ CLIENT_ID }}
