---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterissuer-manager
  labels:
    app.kubernetes.io/name: cert-manager
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["clusterissuers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterissuer-manager-binding
  labels:
    app.kubernetes.io/name: cert-manager
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: clusterissuer-manager
  apiGroup: rbac.authorization.k8s.io

