---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: cluster-config
spec:
  interval: 5m
  targetNamespace: kubewatch
  releaseName: kubewatch
  chart:
    spec:
      chart: kubewatch
      version: "3.5.0"
      sourceRef:
        kind: HelmRepository
        name: kubewatch
        namespace: cluster-config
  values:
    slack:
      enabled: false
    rbac:
      create: true
    namespaceToWatch: "docs"
    resourcesToWatch:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: true
      pod: false
      job: false
      node: false
      clusterrole: false
      clusterrolebinding: false
      serviceaccount: false
      persistentvolume: false
      namespace: false
      secret: false
      configmap: false
      ingress: true
      coreevent: false
      event: false
    webhook:
      enabled: true
      url: "http://webhook.webhook.svc.cluster.local:8080/hook"
