---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: cluster-config
spec:
  interval: 5m
  targetNamespace: kubewatch
  releaseName: kubewatch
  chart:
    spec:
      chart: kubewatch
      version: "3.5.0"
      sourceRef:
        kind: HelmRepository
        name: kubewatch
        namespace: cluster-config
  values:
    rbac:
      create: true
    namespaceToWatch: ""
    resourcesToWatch:
      ingress: true
      services: true
    config:
      handler:
        webhook:
        enabled: true
        url: "http://webhook.webhook.svc.cluster.local:8080/hook"
