---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: cluster-config
spec:
  interval: 5m
  targetNamespace: kubewatch
  releaseName: kubewatch
  chart:
    spec:
      chart: kubewatch
      version: "3.5.0"
      sourceRef:
        kind: HelmRepository
        name: kubewatch
        namespace: cluster-config
  values:
    slack:
      enabled: false
    rbac:
      create: true
    namespaceToWatch: "fortiweb-ingress"
    resourcesToWatch:
      deployment: true
      replicationcontroller: true
      replicaset: true
      daemonset: true
      services: true
      pod: true
      job: true
      node: true
      clusterrole: true
      clusterrolebinding: true
      serviceaccount: true
      persistentvolume: true
      namespace: true
      secret: true
      configmap: true
      ingress: true
      coreevent: true
      event: true
    webhook:
      enabled: true
      url: "http://webhook.webhook.svc.cluster.local:8080/hook"
