---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: cluster-config
spec:
  interval: 5m
  targetNamespace: kubewatch
  releaseName: kubewatch
  chart:
    spec:
      chart: kubewatch
      version: "3.5.0"
      sourceRef:
        kind: HelmRepository
        name: kubewatch-repo
        namespace: cluster-config
  values:
    rbac:
      create: true
    namespaceToWatch: ""
    resourcesToWatch:
      ingress: true
      services: true
