---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubewatch
rules:
  # Core API group resources
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - endpoints
      - replicationcontrollers
      - serviceaccounts
      - nodes
    verbs: ["get", "list", "watch"]

  # Apps API group resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]

  # Networking API group resources
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses  # Ensure full access to ingress resources
    verbs: ["get", "list", "watch"]

  # Events API group resources
  - apiGroups: ["events.k8s.io", ""]
    resources:
      - events
    verbs: ["get", "list", "watch"]

  # RBAC API group resources
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list", "watch"]

  # Batch API group resources
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "watch"]

  # Horizontal Pod Autoscaler
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

  # Custom Resource Definitions (CRDs)
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewatch
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: kubewatch

