---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubewatch
rules:
  - apiGroups: ["", "apps"]
    resources:
      - pods
      - services
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - configmaps
      - secrets
      - events
      - namespaces
      - replicationcontrollers
      - nodes
      - persistentvolumes
      - serviceaccounts
    verbs: ["get", "list", "watch"]
  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources:
      - clusterissuers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "watch"]

