---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cluster-config
spec:
  targetNamespace: cert-manager
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 12h
  values:
    installCRDs: true
  install:
    remediation:
      retries: 3
