---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cluster-config
spec:
  targetNamespace: cert-manager
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 12h
  values:
    installCRDs: true
    podLabels:
      azure.workload.identity/use: "true"
    serviceAccount:
      name: "cert-manager"
      labels:
        azure.workload.identity/use: "true"
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  install:
    remediation:
      retries: 3
