---
apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-intermediate
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
        - name: letsencrypt-intermediate
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              USERNAME=$(kubectl get secret fortiweb-login-secret -o jsonpath="{.data.username}" | base64 -d)
              PASSWORD=$(kubectl get secret fortiweb-login-secret -o jsonpath="{.data.password}" | base64 -d)
              if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
                echo "Error: Could not retrieve username or password from the secret."
                exit 1
              fi
              TOKEN=$(echo "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\",\"vdom\":\"root\"}" | base64 | tr -d "\\n")
              curl 'https://10.0.0.4/api/v2.0/system/certificate.intermediateca' \
                --insecure \
                -H "Authorization:$TOKEN" \
                -k \
                -X 'POST' \
                -H 'Content-Type: multipart/form-data' \
                -H 'Accept: application/json, text/plain, */*' \
                -H 'Accept-Language: en-US,en;q=0.9' \
                -H 'Accept-Encoding: gzip, deflate, br' \
                -H 'Connection: keep-alive' \
                --form "type=localPC" \
                --form "uploadedFile=-----BEGIN CERTIFICATE-----
                MIIFBTCCAu2gAwIBAgIQS6hSk/eaL6JzBkuoBI110DANBgkqhkiG9w0BAQsFADBP
                MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
                Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
                Fw0yNzAzMTIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
                bmNyeXB0MQwwCgYDVQQDEwNSMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
                AoIBAQDPV+XmxFQS7bRH/sknWHZGUCiMHT6I3wWd1bUYKb3dtVq/+vbOo76vACFL
                YlpaPAEvxVgD9on/jhFD68G14BQHlo9vH9fnuoE5CXVlt8KvGFs3Jijno/QHK20a
                /6tYvJWuQP/py1fEtVt/eA0YYbwX51TGu0mRzW4Y0YCF7qZlNrx06rxQTOr8IfM4
                FpOUurDTazgGzRYSespSdcitdrLCnF2YRVxvYXvGLe48E1KGAdlX5jgc3421H5KR
                mudKHMxFqHJV8LDmowfs/acbZp4/SItxhHFYyTr6717yW0QrPHTnj7JHwQdqzZq3
                DZb3EoEmUVQK7GH29/Xi8orIlQ2NAgMBAAGjgfgwgfUwDgYDVR0PAQH/BAQDAgGG
                MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
      restartPolicy: Never
  backoffLimit: 4
