---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cert-manager
  name: configmap-and-secret-reader
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cert-manager
  name: default-serviceaccount-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cert-manager
roleRef:
  kind: Role
  name: configmap-and-secret-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svc-reader
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-serviceaccount-clusterreader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: svc-reader
  apiGroup: rbac.authorization.k8s.io

